name: mysched
description: MySched - An OCR-based mobile app for automated class scheduling and notifications at Immaculate Conception Institutions (ICI).
publish_to: "none"
version: 1.6.0+10

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.8
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.1
  flutter_local_notifications: ^19.5.0
  image_picker: ^1.2.0
  crop_your_image: ^0.7.3
  google_mlkit_text_recognition: ^0.15.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_animate: ^4.3.0
  flutter_slidable: ^3.1.0
  fl_chart: ^0.66.0
  responsive_framework: ^1.3.0
  shimmer: ^3.0.0
  supabase_flutter: ^2.10.3
  share_plus: ^12.0.1
  pdf: ^3.11.3
  intl: ^0.19.0
  path: ^1.9.1
  path_provider: ^2.1.3
  flutter_dotenv: ^5.1.0
  go_router: ^13.2.0
  home_widget: ^0.6.0

dev_dependencies:
  supabase: ^2.10.0

  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  share_plus_platform_interface: ^6.1.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/guides/
    - assets/icon/
  fonts:
    - family: SFProRounded
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Regular.otf
        - asset: assets/fonts/SF-Pro-Rounded-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Rounded-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Rounded-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Rounded-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Rounded-Black.otf
          weight: 900
